// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTUpBUtgu25pJI0woosMuUX9pBJ4qqynI',
    appId: '1:765320440143:web:f96d326c9e20acde1b3d3a',
    messagingSenderId: '765320440143',
    projectId: 'ateek-rosa',
    authDomain: 'ateek-rosa.firebaseapp.com',
    storageBucket: 'ateek-rosa.appspot.com',
    measurementId: 'G-4K4JTPJLGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk11-kN3oP2cXb2HwxcOwx6D0TU_R6YmA',
    appId: '1:765320440143:android:9da58cf167c17e211b3d3a',
    messagingSenderId: '765320440143',
    projectId: 'ateek-rosa',
    storageBucket: 'ateek-rosa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD1oCSFHx22wa7I2mFJSqIDhBdSlsMSDs',
    appId: '1:765320440143:ios:3423e302c34294621b3d3a',
    messagingSenderId: '765320440143',
    projectId: 'ateek-rosa',
    storageBucket: 'ateek-rosa.appspot.com',
    iosClientId: '765320440143-cm8q6oi2s6b79ka0s4ud7fkgk0p01r5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD1oCSFHx22wa7I2mFJSqIDhBdSlsMSDs',
    appId: '1:765320440143:ios:d316aba1da7fff5a1b3d3a',
    messagingSenderId: '765320440143',
    projectId: 'ateek-rosa',
    storageBucket: 'ateek-rosa.appspot.com',
    iosClientId: '765320440143-v4lcek047uom5l1li6a1o1evc7m7ub6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.news',
  );
}
